language: python
python:
- '3.7'
install:
- pip uninstall --yes graphmst || true
- pip install --upgrade --force-reinstall --ignore-installed -e .
- pip install "pytest==4.6.9; python_version != '3.3'" "pytest==2.9.2; python_version == '3.3'" typing
script:
- py.test
- echo Checking whether installation flow is not broken...
- pip uninstall --yes graphmst || true
- pip install --ignore-installed .
- git clone https://${GH_TOKEN}@github.com/chiefsan/GraphMST.git --branch master graphmst
- cd graphmst
- pip install pdoc3
- pdoc graphmst.py --html -o docs/ --force
- rm docs/index.html
- mv docs/graphmst.html docs/index.html
- git add docs/index.html
- git commit -m "Travis #$TRAVIS_BUILD_NUMBER"
- git push --force origin

cache:
  pip: true